# configs/logger/wandb.yaml

_target_: pytorch_lightning.loggers.WandbLogger

project: "contradiction-gfn"
name: null  # Let wandb generate a name
group: "ddp-oom-tests" # Set a group name for this series of tests
log_model: false
mode: offline