# @package callbacks

_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: "checkpoints/"
filename: "debug-step={step}-loss={train/loss:.3f}"
every_n_train_steps: 200
monitor: "train/loss"
mode: "min"
save_top_k: 1