# configs/callbacks/model_checkpoint.yaml

# @package callbacks
_target_: pytorch_lightning.callbacks.ModelCheckpoint
monitor: "val/loss" # We are now logging this
mode: "min"
save_top_k: 1
dirpath: "checkpoints/"
filename: "{epoch}-{step}-{val_loss:.3f}"
# Let's remove every_n_epochs to let val_check_interval control it