# configs/callback/model_checkpoint.yaml

# @package callbacks # This defines the group name for callbacks
# --- CRITICAL CHANGE: This defines this config as an ITEM in a list ---
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/loss"
  mode: "min"
  save_top_k: 1
  dirpath: "checkpoints/"
  filename: "{epoch}-{step}-{val_loss:.3f}"
  every_n_epochs: 1
# --- END CRITICAL CHANGE ---