
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "/home/data/zeshenghong/checkpoints/gfn_project/ddp_debug_checkpoints/"
  save_last: true
  monitor: "train/loss_step"
  mode: "min"
  save_top_k: 1
  every_n_train_steps: 2
  save_on_train_epoch_end: false
  filename: "ddp-debug-step={step}"

